### ISSUE TITLE
Cannot run the nginx exporter

### ISSUE THREAD

**Issue by bradmccormack** [discordianfish/nginx_exporter#1]
/usr/lib/go/src/pkg/github.com/prometheus/client_golang/prometheus/registry.go:36:2: import "bitbucket.org/ww/goautoneg": cannot find package

go get -d doesn't help.

Get https://api.bitbucket.org/1.0/repositories/ww/goautoneg: x509: certificate signed by unknown authority

Wrong endpoint now?

**Comment by discordianfish** [comment]
Can you try again? Either it was a temporary issue or you miss the root certificates the bitbucket TLS cert was signed with.

**Comment by discordianfish** [comment]
Assuming this works now.
