### ISSUE TITLE
Monitor multi nginx.scrape_uri

### ISSUE THREAD

**Issue by regardfs** [discordianfish/nginx_exporter#19]
Hi, I have the US of monitor multi nginx.scrape_uri, It seems not support monitor config like 
     
>   -nginx.scrape_uri=http://172.0.0.101/ngx_status
      -nginx.scrape_uri=http://172.0.0.102/ngx_status

So , I have to hard code and initial docker with these config

>   nginx-exporter1:
    image: fish/nginx-exporter
    ports:
      - 9113:9113
    command:
      - -nginx.scrape_uri=http://172.0.0.101/ngx_status

> nginx-exporter2:
    image: fish/nginx-exporter
    ports:
      - 9114:9113
    command:
      - -nginx.scrape_uri=http://172.0.0.102/ngx_status

So, is there any best practice for this kind of scenario?

**Comment by julian-eggers** [comment]
I have the same scenario but I would prefer a service-discovery based solution via dns a-records.

**Comment by regardfs** [comment]
@julian-eggers, thanks for u suggestion, I will try, for now , I use file_sd_file config to simulate the auto discovery
