### ISSUE TITLE
New Docker images fail to start for us?

### ISSUE THREAD

**Issue by EdSchouten** [discordianfish/nginx_exporter#23]
Hi,

Quick bug report to ensure impact is minimalized. It may be the case that the latest version of the Docker images (from a couple of hours ago) fail with this:
```
/bin/nginx_exporter: relocation error: /lib/libpthread.so.0: symbol h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

HTH,
Ed

**Comment by silvpol** [comment]
Same here, earlier version works fine, latest fails with the same error.

**Comment by EdSchouten** [comment]
This is broken for more than a month now.

**Comment by ajardan** [comment]
Had the same issue, so I fixed and pushed an image from my fork. You can temporarily use m4cros/nginx_exporter until @discordianfish has time to fix his image.
