### ISSUE TITLE
Consider to use dep and semver releases

### ISSUE THREAD

**Issue by wjkohnen** [discordianfish/nginx_exporter#26]
Please consider to use dep tool in order to create reproducible builds and to release them using semantic versioning.

**Comment by atombender** [comment]
Also, _please_ push Docker images using a versioned tag and/or commit ID. We're being hit by #23, and there's no way to roll back to the version that did work, because the only tag is `latest`, which has been overwritten.

**Comment by wjkohnen** [comment]
Until this is fixed you could use [my fork](https://hub.docker.com/r/wjkohnen/nginx_exporter/).

**Comment by atombender** [comment]
@wjkohnen Thanks!

**Comment by wjkohnen** [comment]
I guess, this can be closed, too. There is an autobuilt docker image with a semver tag available now, see README. :)
