### ISSUE TITLE
Error starting latest build

### ISSUE THREAD

**Issue by discostur** [discordianfish/nginx_exporter#30]
Getting the following error if i try to start the latest container:

```
/bin/nginx_exporter: relocation error: /lib/libpthread.so.0: symbol h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

**Comment by EdSchouten** [comment]
Hi there!

This is a duplicate of #23. Any chance this will be fixed in the nearby future?

**Comment by ajardan** [comment]
Had the same issue, so I fixed and pushed an image from my fork. You can temporarily use m4cros/nginx_exporter until @discordianfish has time to fix his image.

**Comment by EdSchouten** [comment]
You're a watcher of the repository, so you should already receive issue/PR notifications. Are you sure your email address of your GitHub account is configured properly?

**Comment by discordianfish** [comment]
I disabled notifications for watched repos because I have to many of them and so far haven't cleaned that up. Wish there would be at least some way to batch-edit this.

**Comment by ajardan** [comment]
I guess this can be closed now ?
